# Generated by Django 6.1 on 2026-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(default='NOT ADDED YET', max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='time_range_display',
            field=models.CharField(default='Mmm yyyy - Mmm yyyy', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.JSONField(default=list),
        ),
    ]
