# Generated by Django 6.1 on 2026-09-12 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year_display', models.CharField(max_length=255)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('verification_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
